import math
print(math.cos(0.00))
print(math.cos(1))
print(math.cos(10))
print("__________________________________")
print(math.sin(0))
print(math.sin(1))
print(math.sin(10))
print("__________________________________")
print(math.degrees(8.90))
print(math.degrees(1))
print(math.degrees(10))
print("__________________________________")
print(math.fabs(-10))
print(math.fabs(-5.9))
print(math.fabs(5.7))

